In [1]:
import pandas as pd

import numpy as np

In [2]:
WorldCupMatches = 'WorldCupMatches.csv'
WorldCupPlayers = 'WorldCupPlayers.csv'
WorldCups = 'WorldCups.csv'

In [3]:
df_mat = pd.read_csv(WorldCupMatches)
df_pla = pd.read_csv(WorldCupPlayers)
df_wc = pd.read_csv(WorldCups)

In [7]:
#Check percentage of empty cells per column
for x in df_mat.columns:
    print(f"The percentage of empty cells in column {x} is {round(df_mat[x].isna().sum()/len(df_mat[x])*100,2)} %.")

The percentage of empty cells in column Year is 81.36 %.
The percentage of empty cells in column Datetime is 81.36 %.
The percentage of empty cells in column Stage is 81.36 %.
The percentage of empty cells in column Stadium is 81.36 %.
The percentage of empty cells in column City is 81.36 %.
The percentage of empty cells in column Home Team Name is 81.36 %.
The percentage of empty cells in column Home Team Goals is 81.36 %.
The percentage of empty cells in column Away Team Goals is 81.36 %.
The percentage of empty cells in column Away Team Name is 81.36 %.
The percentage of empty cells in column Win conditions is 81.36 %.
The percentage of empty cells in column Attendance is 81.41 %.
The percentage of empty cells in column Half-time Home Goals is 81.36 %.
The percentage of empty cells in column Half-time Away Goals is 81.36 %.
The percentage of empty cells in column Referee is 81.36 %.
The percentage of empty cells in column Assistant 1 is 81.36 %.
The percentage of empty cells in column Assistant 2 is 81.36 %.
The percentage of empty cells in column RoundID is 81.36 %.
The percentage of empty cells in column MatchID is 81.36 %.
The percentage of empty cells in column Home Team Initials is 81.36 %.
The percentage of empty cells in column Away Team Initials is 81.36 %.

In [8]:
#Check percentage of empty cells per column
for x in df_pla.columns:
    print(f"The percentage of empty cells in column {x} is {round(df_pla[x].isna().sum()/len(df_pla[x])*100,2)} %.")

The percentage of empty cells in column RoundID is 0.0 %.
The percentage of empty cells in column MatchID is 0.0 %.
The percentage of empty cells in column Team Initials is 0.0 %.
The percentage of empty cells in column Coach Name is 0.0 %.
The percentage of empty cells in column Line-up is 0.0 %.
The percentage of empty cells in column Shirt Number is 0.0 %.
The percentage of empty cells in column Player Name is 0.0 %.
The percentage of empty cells in column Position is 89.04 %.
The percentage of empty cells in column Event is 76.0 %.

In [9]:
#Check percentage of empty cells per column
for x in df_wc.columns:
    print(f"The percentage of empty cells in column {x} is {round(df_wc[x].isna().sum()/len(df_wc[x])*100,2)} %.")

The percentage of empty cells in column Year is 0.0 %.
The percentage of empty cells in column Country is 0.0 %.
The percentage of empty cells in column Winner is 0.0 %.
The percentage of empty cells in column Runners-Up is 0.0 %.
The percentage of empty cells in column Third is 0.0 %.
The percentage of empty cells in column Fourth is 0.0 %.
The percentage of empty cells in column GoalsScored is 0.0 %.
The percentage of empty cells in column QualifiedTeams is 0.0 %.
The percentage of empty cells in column MatchesPlayed is 0.0 %.
The percentage of empty cells in column Attendance is 0.0 %.

In [10]:
#Deleted empty rows
df_mat = df_mat.dropna(how='all')
df_mat

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
847,2014.0,05 Jul 2014 - 17:00,Quarter-finals,Arena Fonte Nova,Salvador,Netherlands,0.0,0.0,Costa Rica,Netherlands win on penalties (4 - 3),51179.0,0.0,0.0,Ravshan IRMATOV (UZB),RASULOV Abduxamidullo (UZB),KOCHKAROV Bakhadyr (KGZ),255953.0,300186488.0,NED,CRC
848,2014.0,08 Jul 2014 - 17:00,Semi-finals,Estadio Mineirao,Belo Horizonte,Brazil,1.0,7.0,Germany,,58141.0,0.0,5.0,RODRIGUEZ Marco (MEX),TORRENTERA Marvin (MEX),QUINTERO Marcos (MEX),255955.0,300186474.0,BRA,GER
849,2014.0,09 Jul 2014 - 17:00,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,Argentina win on penalties (2 - 4),63267.0,0.0,0.0,C�neyt �AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
850,2014.0,12 Jul 2014 - 17:00,Play-off for third place,Estadio Nacional,Brasilia,Brazil,0.0,3.0,Netherlands,,68034.0,0.0,2.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255957.0,300186502.0,BRA,NED
851,2014.0,13 Jul 2014 - 16:00,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,Germany win after extra time,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

In [11]:
#Delete duplicate rows
df_mat = df_mat.drop_duplicates()
df_mat

,Year,Datetime,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
831,2014.0,05 Jul 2014 - 13:00,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1.0,0.0,Belgium,,68551.0,1.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953.0,300186504.0,ARG,BEL
832,2014.0,29 Jun 2014 - 13:00,Round of 16,Estadio Castelao,Fortaleza,Netherlands,2.0,1.0,Mexico,,58817.0,0.0,0.0,PROENCA Pedro (POR),MIRANDA Bertino (POR),TRIGO Jose (POR),255951.0,300186508.0,NED,MEX
833,2014.0,29 Jun 2014 - 17:00,Round of 16,Arena Pernambuco,Recife,Costa Rica,1.0,1.0,Greece,Costa Rica win on penalties (5 - 3),41242.0,0.0,0.0,Ben WILLIAMS (AUS),CREAM Matthew (AUS),ANAZ Hakan (AUS),255951.0,300186459.0,CRC,GRE
834,2014.0,01 Jul 2014 - 13:00,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1.0,0.0,Switzerland,Argentina win after extra time,63255.0,0.0,0.0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951.0,300186503.0,ARG,SUI
835,2014.0,01 Jul 2014 - 17:00,Round of 16,Arena Fonte Nova,Salvador,Belgium,2.0,1.0,USA,Belgium win after extra time,51227.0,0.0,0.0,HAIMOUDI Djamel (ALG),ACHIK Redouane (MAR),ETCHIALI Abdelhak (ALG),255951.0,300186497.0,BEL,USA

In [12]:
#Delete duplicate rows
df_pla = df_pla.drop_duplicates()
df_pla

,RoundID,MatchID,Team Initials,Coach Name,Line-up,Shirt Number,Player Name,Position,Event
0,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Alex THEPOT,GK,NaN
1,201,1096,MEX,LUQUE Juan (MEX),S,0,Oscar BONFIGLIO,GK,NaN
2,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Marcel LANGILLER,NaN,G40'
3,201,1096,MEX,LUQUE Juan (MEX),S,0,Juan CARRENO,NaN,G70'
4,201,1096,FRA,CAUDRON Raoul (FRA),S,0,Ernest LIBERATI,NaN,NaN
...,...,...,...,...,...,...,...,...,...
37043,255951,300186497,USA,KLINSMANN Juergen (GER),N,17,ALTIDORE,NaN,NaN
37044,255951,300186497,BEL,WILMOTS Marc (BEL),N,16,DEFOUR,NaN,NaN
37045,255951,300186497,USA,KLINSMANN Juergen (GER),N,18,WONDOLOWSKI,NaN,I72'
37046,255951,300186497,BEL,WILMOTS Marc (BEL),N,21,VANDEN BORRE,NaN,NaN
37047,255951,300186497,USA,KLINSMANN Juergen (GER),N,21,CHANDLER,NaN,NaN

In [13]:
#Delete duplicate rows
df_wc = df_wc.drop_duplicates()
df_wc

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810

In [19]:
#Use the fillna() function to replace NaN with 0 and then convert to int
df_mat['Attendance'] = df_mat['Attendance'].fillna(0).astype(int)

#Check the result
print(df_mat['Attendance'].head())

0     4444
1    18346
2    24059
3     2549
4    23409
Name: Attendance, dtype: int32

C:\Users\barba\AppData\Local\Temp\ipykernel_10476\296061137.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat['Attendance'] = df_mat['Attendance'].fillna(0).astype(int)

In [20]:
#Change data type of each column
df_mat['Year'] = df_mat['Year'].astype('int64')
df_mat['RoundID'] = df_mat['RoundID'].astype('int64')
df_mat['MatchID'] = df_mat['MatchID'].astype('int64')
df_mat['Attendance'] = df_mat['Attendance'].astype('int64')

C:\Users\barba\AppData\Local\Temp\ipykernel_10476\898581954.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat['Year'] = df_mat['Year'].astype('int64')
C:\Users\barba\AppData\Local\Temp\ipykernel_10476\898581954.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat['RoundID'] = df_mat['RoundID'].astype('int64')
C:\Users\barba\AppData\Local\Temp\ipykernel_10476\898581954.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat['MatchID'] = df_mat['MatchID'].astype('int64')
C:\Users\barba\AppData\Local\Temp\ipykernel_10476\898581954.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat['Attendance'] = df_mat['Attendance'].astype('int64')

In [22]:
#Rename columns
df_mat.rename(columns={'Year': 'year_id'}, inplace=True)
print(df_mat.head())

#Rename columns
df_wc.rename(columns={'Year': 'year_id'}, inplace=True)
print(df_wc.head())

   year_id              Datetime    Stage         Stadium         City  \
0     1930  13 Jul 1930 - 15:00   Group 1         Pocitos  Montevideo
1     1930  13 Jul 1930 - 15:00   Group 4  Parque Central  Montevideo
2     1930  14 Jul 1930 - 12:45   Group 2  Parque Central  Montevideo
3     1930  14 Jul 1930 - 14:50   Group 3         Pocitos  Montevideo
4     1930  15 Jul 1930 - 16:00   Group 1  Parque Central  Montevideo

  Home Team Name  Home Team Goals  Away Team Goals Away Team Name  \
0         France              4.0              1.0         Mexico
1            USA              3.0              0.0        Belgium
2     Yugoslavia              2.0              1.0         Brazil
3        Romania              3.0              1.0           Peru
4      Argentina              1.0              0.0         France

  Win conditions  Attendance  Half-time Home Goals  Half-time Away Goals  \
0                       4444                   3.0                   0.0
1                      18346                   2.0                   0.0
2                      24059                   2.0                   0.0
3                       2549                   1.0                   0.0
4                      23409                   0.0                   0.0

                  Referee               Assistant 1  \
0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)
1       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)
2     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)
3   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)
4     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)

                  Assistant 2  RoundID  MatchID Home Team Initials  \
0         REGO Gilberto (BRA)      201     1096                FRA
1       WARNKEN Alberto (CHI)      201     1090                USA
2         BALWAY Thomas (FRA)      201     1093                YUG
3    MATEUCCI Francisco (URU)      201     1098                ROU
4  RADULESCU Constantin (ROU)      201     1085                ARG

  Away Team Initials
0                MEX
1                BEL
2                BRA
3                PER
4                FRA

C:\Users\barba\AppData\Local\Temp\ipykernel_10476\185504391.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_mat.rename(columns={'Year': 'year_id'}, inplace=True)

In [23]:
#Sort columns
first_columns = ['MatchID', 'year_id', 'RoundID']
other_columns = [col for col in df_mat.columns if col not in first_columns]
df_mat = df_mat[first_columns + other_columns]
print(df_mat.head())

   MatchID  year_id  RoundID              Datetime    Stage         Stadium  \
0     1096     1930      201  13 Jul 1930 - 15:00   Group 1         Pocitos
1     1090     1930      201  13 Jul 1930 - 15:00   Group 4  Parque Central
2     1093     1930      201  14 Jul 1930 - 12:45   Group 2  Parque Central
3     1098     1930      201  14 Jul 1930 - 14:50   Group 3         Pocitos
4     1085     1930      201  15 Jul 1930 - 16:00   Group 1  Parque Central

          City Home Team Name  Home Team Goals  Away Team Goals  \
0  Montevideo          France              4.0              1.0
1  Montevideo             USA              3.0              0.0
2  Montevideo      Yugoslavia              2.0              1.0
3  Montevideo         Romania              3.0              1.0
4  Montevideo       Argentina              1.0              0.0

  Away Team Name Win conditions  Attendance  Half-time Home Goals  \
0         Mexico                       4444                   3.0
1        Belgium                      18346                   2.0
2         Brazil                      24059                   2.0
3           Peru                       2549                   1.0
4         France                      23409                   0.0

   Half-time Away Goals                 Referee               Assistant 1  \
0                   0.0  LOMBARDI Domingo (URU)     CRISTOPHE Henry (BEL)
1                   0.0       MACIAS Jose (ARG)  MATEUCCI Francisco (URU)
2                   0.0     TEJADA Anibal (URU)   VALLARINO Ricardo (URU)
3                   0.0   WARNKEN Alberto (CHI)       LANGENUS Jean (BEL)
4                   0.0     REGO Gilberto (BRA)      SAUCEDO Ulises (BOL)

                  Assistant 2 Home Team Initials Away Team Initials
0         REGO Gilberto (BRA)                FRA                MEX
1       WARNKEN Alberto (CHI)                USA                BEL
2         BALWAY Thomas (FRA)                YUG                BRA
3    MATEUCCI Francisco (URU)                ROU                PER
4  RADULESCU Constantin (ROU)                ARG                FRA

In [27]:
#Deletes columns
df_pla = df_pla.drop(columns=['Shirt Number', 'Position', 'Event'])
df_pla.dtypes

RoundID           int64
MatchID           int64
Team Initials    object
Coach Name       object
Line-up          object
Player Name      object
dtype: object

In [28]:
#Add index
df_pla['player_id'] = range(1, len(df_pla) + 1)
print(df_pla.head())

   RoundID  MatchID Team Initials           Coach Name Line-up  \
0      201     1096           FRA  CAUDRON Raoul (FRA)       S
1      201     1096           MEX     LUQUE Juan (MEX)       S
2      201     1096           FRA  CAUDRON Raoul (FRA)       S
3      201     1096           MEX     LUQUE Juan (MEX)       S
4      201     1096           FRA  CAUDRON Raoul (FRA)       S

        Player Name  player_id
0       Alex THEPOT          1
1   Oscar BONFIGLIO          2
2  Marcel LANGILLER          3
3      Juan CARRENO          4
4   Ernest LIBERATI          5

In [29]:
#Sort columns
columns = ['player_id'] + [col for col in df_pla if col != 'player_id']
df_pla = df_pla[columns]
print(df_pla.head())

   player_id  RoundID  MatchID Team Initials           Coach Name Line-up  \
0          1      201     1096           FRA  CAUDRON Raoul (FRA)       S
1          2      201     1096           MEX     LUQUE Juan (MEX)       S
2          3      201     1096           FRA  CAUDRON Raoul (FRA)       S
3          4      201     1096           MEX     LUQUE Juan (MEX)       S
4          5      201     1096           FRA  CAUDRON Raoul (FRA)       S

        Player Name
0       Alex THEPOT
1   Oscar BONFIGLIO
2  Marcel LANGILLER
3      Juan CARRENO
4   Ernest LIBERATI

In [37]:
#df_mat.to_csv('matches_to_SQL.csv', index=False)

In [38]:
#df_pla.to_csv('players_to_SQL.csv', index=False)

In [39]:
#df_wc.to_csv('wc_to_SQL.csv', index=False)